# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7adabafd44fddceec5c43d3509b6f9ff02f9ddb7a9b62921685f1fc1e66fa6cdbeb478f5cfa6370789143c40fd9b1601c7abf501b999f2aba9dc79d9a89ab9c

test:
  secret_key_base: 4c48c548d4bf8d11d37e199be10f0c4ec528773d6b66b7468eb99cfdaec987f0c50dd981532863877815022b8a8052457ebeacbbc3dabdc2bbe3e7e83164af84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
